[workspace]
members = [
    "path_utils",
    "find_dir",
    "is_prime",
    "boggle"
]

[workspace.dependencies]
clap = { version = "4.0", features = ["derive"] }
rand = "0.8"
tui = "0.19"
crossterm = "0.25"
lazy_static = "1.4"
reqwest = "0.11"
tokio = { version = "1", features = ["full"] }
futures = "0.3"