CREATE TABLE chats (
	id BLOB PRIMARY KEY DEFAULT(randomblob(16)),
	name TEXT NOT NULL
) STRICT, WITHOUT ROWID;

CREATE TABLE messages (
	id INTEGER PRIMARY KEY,
	chat BLOB NOT NULL,
	content TEXT NOT NULL,
	creation_time TEXT NOT NULL DEFAULT(CURRENT_TIMESTAMP),
	FOREIGN KEY(chat) REFERENCES chats(id) ON DELETE CASCADE
) STRICT;
