CREATE TABLE chats (
	id BLOB PRIMARY KEY DEFAULT(randomblob(16)),
	name VARCHAR(100) NOT NULL
) WITHOUT ROWID;

CREATE TABLE messages (
	id INTEGER PRIMARY KEY,
	chat BLOB NOT NULL,
	content TEXT NOT NULL,
	FOREIGN KEY(chat) REFERENCES chats(id) ON DELETE CASCADE
);
