[package]
name = "find_dir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cli-clipboard = "0.4"
inquire = "0.6"
thiserror = "1.0.39"
